### ISSUE TITLE
Include Handlebars in index-test.js

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#1]
Previous module introduced using Handlebars with API calls, makes much more sense to let us use it in this lab!

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @f3mshep.

We are in the process of updating the materials in this section and will update or possibly remove this lesson referencing the issues that have been opened.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
