### ISSUE TITLE
unprepared

### ISSUE THREAD

**Issue by hdanziger** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#2]
i feel unprepared for this lab. there are components within it that i do not feel were covered in any lessons prior to this lab.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @hdanziger.

We are in the process of updating the materials in this section and will update or possibly remove this lesson referencing the issues that have been opened.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
