### ISSUE TITLE
Solution doesn't work / somewhat confusing instructions 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#3]
@cernanb 
The solution for this repo doesn't pass due to missing elements in the `index.html` file. There is no text input, nor a link to link to submit the request with the input. Also, it is a bit strange to have a link rather than a form or a button. If the directions are not carefully read, many students miss that they need a link rather than a regular form. It is kind of a "gotcha" requirement to require a link.

**Comment by hansenjl** [comment]
@cernanb 
I second this comment. When the handlebars components were removed from this lab, these 2 lines of code from the html were also removed:
```
<input type="text" id="searchTerms">	
<a href="#" id="search" onclick="searchRepositories()">Search Repositories</a>
```

Students typically don't realize that this is something they have to add in and are confused about where the search term is coming from.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kwebster2 and @hansenjl.

We are in the process of updating the materials in this section and will update or possibly remove this lesson referencing the issues that have been opened.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
