### ISSUE TITLE
Regex In index-test.js Does Not Render Forward Slashes as Escaped

### ISSUE THREAD

**Issue by tpetersen0308** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#4]
The regex in line 58 does not render the character escapes when running the test suite, creating the following error:

regex:
`expect(requests[0].url).toMatch(/https:\/\/api.github.com\/search\/repositories?q=tetris/)`

error:
`  1) index.js ajax functions searchRepositories calls out to the github search API and displays results:
     Error: Expected 'https://api.github.com/search/repositories?q=tetris' to match /https:\/\/api.github.com\/search\/repositories?q=tetris/
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toMatch (node_modules/expect/lib/Expectation.js:138:28)
      at Context.it (test/index-test.js:58:33)`

The same issue occurs with the regex in line 68. I changed the regex to string literals in my fork to get the tests passing because AAQ was down and I needed to move forward with the material.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @tpetersen0308.

We are in the process of updating the materials in this section and will update or possibly remove this lesson referencing the issues that have been opened.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
