### ISSUE TITLE
Tests suite dependency issue

### ISSUE THREAD

**Issue by mrfarmer777** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#5]
Receiving the following error when running the tests:
`1) index.js "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @mrfarmer777.

We have updated the materials, fixed the package issue causing this error, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
