### ISSUE TITLE
Test Not Running error: before all" hook:

### ISSUE THREAD

**Issue by YanezDiego** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#6]
Keep getting this error while I run the learn command 
`index.js "before all" hook:`
even after finishing the lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @YanezDiego.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
