### ISSUE TITLE
Using "learn" command returns an error

### ISSUE THREAD

**Issue by tech-chieftain** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#8]
Using the learn command returns an error and displays that the local test has been passed although I haven't done anything.

The error is:
index.js "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

**Comment by drakeltheryuujin** [comment]
Hi @tech-chieftain,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
