### ISSUE TITLE
Solution is not updated in index.html

### ISSUE THREAD

**Issue by pcherian10** [learn-co-curriculum/js-ajax-ajax-and-callbacks-lab#9]
Does not address how to create a form or / link to searchRepositories() function.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in #7 .  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
